export const CONTACTS = [
  {
    id: "anna",
    name: "Anna",
    initials: "AN",
    color: "#ff6b9d",
    gradient: ["#ff9a9e", "#ff6b9d"],
    photo: "/avatar-anna.jpg",
    subtitle: "Barátnő · laza & kedves",
    greeting: "Hey! Wie geht's dir heute? Was hast du heute gemacht?",
  },
  {
    id: "prof",
    name: "Prof. Weber",
    initials: "PW",
    color: "#5856d6",
    gradient: ["#667eea", "#5856d6"],
    photo: "/avatar-prof.jpg",
    subtitle: "Tanár · formális & precíz",
    greeting: "Guten Tag! Womit kann ich Ihnen heute behilflich sein?",
  },
  {
    id: "marco",
    name: "Marco",
    initials: "MA",
    color: "#ff6b35",
    gradient: ["#f7971e", "#ff6b35"],
    photo: "/avatar-marco.jpg",
    subtitle: "Olasz Berlinben · vicces & laza",
    greeting: "Ciao! Alles gut bei dir? Berlin ist heute bellissimo!",
  },
  {
    id: "lena",
    name: "Lena",
    initials: "LE",
    color: "#00b894",
    gradient: ["#11998e", "#00b894"],
    photo: "/avatar-lena.jpg",
    subtitle: "Startup · business casual",
    greeting: "Hey! Was machst du so? Ich komme gerade aus einem Meeting 😅",
  },
];
